"""Per-box network plumbing (DESIGN-BOXES.md, WP1).

Two halves:

- `render_ruleset()` renders the multi-box nft ruleset. The checked-in
  `vm/net/jarvis-egress-boxes.nft` IS its output (a golden-file test holds the
  two equal), and the root-run script loads the checked-in file, never a file
  the app wrote: the app user must not be able to choose what the firewall
  says.
- `add(box)` / `delete(box)` run `vm/net/net_box.sh` under `sudo -n` to create
  a box's tap and pin it in the nft sets. The script re-derives every address
  from the tap number and refuses anything else, so even a compromised app
  can only pin 10.201.N.1/.2 to jvtapN.

The pinning model: `guest_taps` names the guest-facing interfaces;
`tap_addr` (ifname . host IP) and `tap_src` (ifname . guest IP) must BOTH
match for a packet from a guest to reach the host at all. A box therefore
cannot spoof another box's source address, cannot dial another box's proxy
listener, and cannot reach any other host address (LAN IP included).
Forwarding from guests is dropped outright: boxes cannot reach each other or
the LAN; the host proxy is the only way out.
"""
import asyncio
import hashlib
import re

from .. import config
from ..config import settings

DNS_PORT = 53
PROXY_PORT = 8443


def render_ruleset(*, table: str = "jarvis_vm", shared_tap: str = "jvtap0",
                   shared_host_ip: str = "10.201.0.1",
                   shared_guest_ip: str = "10.201.0.2",
                   proxy_port: int = PROXY_PORT) -> str:
    """The flag-on ruleset. Pure; the defaults render the checked-in file."""
    return f"""\
# Monitored-egress ruleset, MULTI-BOX mode (vm_boxes_enabled). GENERATED by
# backend/vm/boxnet.render_ruleset() -- edit that and regenerate; a golden-file
# test (tests/test_boxnet.py) holds this file equal to the renderer.
#
# Every guest-facing interface (a KVM box's tap, a docker box's bridge) is in
# @guest_taps. A packet from one reaches the host ONLY if its (iif, saddr) is
# in @tap_src AND its (iif, daddr) is in @tap_addr: no spoofing another box's
# address, no dialing another box's proxy listener, no other host address.
# Then only DNS, the proxy port and ping. Forwarding from guests is dropped:
# boxes cannot reach each other or the LAN. net_box.sh adds/removes the pins.
#
# Self-replacing: the two-line preamble means `nft -f` always starts clean.
table inet {table}
delete table inet {table}

table inet {table} {{
    set cut_hosts {{ type ipv4_addr; flags interval; }}
    set guest_taps {{ type ifname; elements = {{ "{shared_tap}" }} }}
    set tap_addr {{ type ifname . ipv4_addr; elements = {{ "{shared_tap}" . {shared_host_ip} }} }}
    set tap_src {{ type ifname . ipv4_addr; elements = {{ "{shared_tap}" . {shared_guest_ip} }} }}

    chain input {{
        type filter hook input priority -10; policy accept;
        iifname @guest_taps jump guest_input
    }}

    # Guest -> host. Pins first (before conntrack's established accept, so a
    # forged packet cannot ride another box's flow), then the three services.
    chain guest_input {{
        meta nfproto ipv6 counter drop
        # DHCP for the shared box only (its pinned lease; other boxes are
        # configured from box.json): before it has an address its source is
        # 0.0.0.0, which the pins below would drop.
        iifname "{shared_tap}" ip saddr 0.0.0.0 ip daddr 255.255.255.255 udp sport 68 udp dport 67 accept
        iifname . ip saddr != @tap_src limit rate 10/second counter log prefix "jvm-spoof " drop
        iifname . ip saddr != @tap_src counter drop
        iifname . ip daddr != @tap_addr limit rate 10/second counter log prefix "jvm-xbox " drop
        iifname . ip daddr != @tap_addr counter drop
        ct state established,related accept
        udp dport {DNS_PORT} accept
        tcp dport {DNS_PORT} accept
        tcp dport {proxy_port} accept
        icmp type echo-request accept
        limit rate 10/second counter log prefix "jvm-host-drop " drop
        counter drop
    }}

    chain forward {{
        # policy ACCEPT: this table polices Jav3's guest taps only. A drop policy
        # here also dropped every other forwarded packet on the host (Docker's
        # bridge: image builds and the operator's own containers, 2026-09-27).
        type filter hook forward priority -10; policy accept;
        iifname @guest_taps jump guest_forward
        oifname @guest_taps ct state established,related accept
        oifname @guest_taps counter drop
    }}

    # No guest has a legitimate forward path (all egress is via the host proxy).
    chain guest_forward {{
        ip daddr @cut_hosts counter log prefix "jvm-cut " drop
        counter log prefix "jvm-egress-drop " drop
    }}

    # Host output: a cut host is unreachable even from the proxy itself.
    chain output {{
        type filter hook output priority -10; policy accept;
        ip daddr @cut_hosts counter log prefix "jvm-cut-out " drop
    }}
}}
"""


DEFAULT_TABLE = "jarvis_vm"
_INSTANCE_RE = re.compile(r"^[a-z0-9]{1,12}$")
_TAP_RE = re.compile(r"^jvtap(0|[1-9][0-9]{0,2})$")


def instance() -> str:
    """This install's host-network instance name: "" for the default install,
    settings.instance when set, else a short hash of a non-default
    JARVIS_CONFIG_DIR. Names the nft table, pid files, dns log and pcaps."""
    name = (settings.instance or "").strip()
    if name:
        if not _INSTANCE_RE.match(name):
            raise ValueError(f"JARVIS_INSTANCE {name!r}: 1-12 of [a-z0-9]")
        return name
    if config.CONFIG_DIR.resolve() != config.DEFAULT_CONFIG_DIR.resolve():
        return hashlib.sha1(str(config.CONFIG_DIR.resolve()).encode()).hexdigest()[:8]
    return ""


def nft_table() -> str:
    inst = instance()
    return f"{DEFAULT_TABLE}_{inst}" if inst else DEFAULT_TABLE


def shared_net() -> dict:
    """The shared box's tap / host IP, checked. Raises ValueError when they do
    not agree (jvtapN <-> 10.201.N.1), or when a named instance would take the
    default install's jvtap0 / CID 3: that is how a second instance tore down
    the live one's tap and tcpdump (e2e BUG-1)."""
    tap = settings.vm_egress_tap
    m = _TAP_RE.match(tap or "")
    if not m or int(m.group(1)) > 254:
        raise ValueError(f"vm_egress_tap {tap!r}: must be jvtapN, N in 0..254")
    n = int(m.group(1))
    if settings.vm_egress_host_ip != f"10.201.{n}.1":
        raise ValueError(f"vm_egress_host_ip must be 10.201.{n}.1 for {tap}")
    if instance() and (n == 0 or settings.vm_guest_cid == 3):
        raise ValueError(
            "a named instance must not use the default install's jvtap0 / CID 3: "
            "set JARVIS_VM_EGRESS_TAP=jvtapN, JARVIS_VM_EGRESS_HOST_IP=10.201.N.1 "
            "and JARVIS_VM_GUEST_CID")
    return {"tap": tap, "host_ip": settings.vm_egress_host_ip}


def net_up_argv(action: str) -> list[str]:
    """The exact argv for `net_up.sh` under sudo. sudo's env_reset strips
    JARVIS_*, so everything goes in argv, validated again by the script. The
    default install with default values keeps the bare `net_up.sh <action>`
    its existing sudoers line matches."""
    if action not in ("up", "down", "up-boxes", "down-boxes"):
        raise ValueError(action)
    net = shared_net()
    argv = ["sudo", "-n", "bash",
            str(settings.base_dir / "vm" / "net" / "net_up.sh"), action]
    extra = [net["tap"], net["host_ip"], "1" if settings.vm_egress_pcap else "0",
             nft_table()]
    if extra != ["jvtap0", "10.201.0.1", "1", DEFAULT_TABLE]:
        argv += extra
    return argv


def _script():
    return settings.base_dir / "vm" / "net" / "net_box.sh"


def net_box_argv(action: str, box) -> list[str]:
    """The exact argv run under sudo (the sudoers line matches this shape).
    A named instance appends its nft table (env would be stripped by sudo)."""
    if action not in ("add", "del", "pin", "unpin"):
        raise ValueError(action)
    argv = ["sudo", "-n", "bash", str(_script()), action, box.tap,
            box.host_ip, box.guest_ip]
    if nft_table() != DEFAULT_TABLE:
        argv.append(nft_table())
    return argv


async def _run(action: str, box) -> None:
    proc = await asyncio.create_subprocess_exec(
        *net_box_argv(action, box), stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.PIPE)
    _, err = await proc.communicate()
    if proc.returncode:
        raise RuntimeError(f"net_box.sh {action} {box.tap}: "
                           f"{err.decode(errors='replace')[:300]}")


async def add(box) -> None:
    """Create the box's tap and pin it. Raises on failure (the boot is then
    refused: fail closed)."""
    await _run("pin" if box.runtime == "docker" else "add", box)


async def delete(box) -> None:
    """Unpin and remove. Best-effort: a box going away must finish going."""
    try:
        await _run("unpin" if box.runtime == "docker" else "del", box)
    except (RuntimeError, OSError) as e:
        print(f"[boxes] net del {box.tap} failed: {e}")


if __name__ == "__main__":       # python -m backend.vm.boxnet > vm/net/jarvis-egress-boxes.nft
    print(render_ruleset(), end="")
