"""Per-box network plumbing (DESIGN-BOXES.md, WP1).

Two halves:

- `render_ruleset()` renders the multi-box nft ruleset. The checked-in
  `vm/net/jarvis-egress-boxes.nft` IS its output (a golden-file test holds the
  two equal), and the root-run script loads the checked-in file, never a file
  the app wrote: the app user must not be able to choose what the firewall
  says.
- `add(box)` / `delete(box)` run `vm/net/net_box.sh` under `sudo -n` to create
  a box's tap and pin it in the nft sets. The script re-derives every address
  from the tap number and refuses anything else, so even a compromised app
  can only pin 10.201.N.1/.2 to jvtapN.

The pinning model: `guest_taps` names the guest-facing interfaces;
`tap_addr` (ifname . host IP) and `tap_src` (ifname . guest IP) must BOTH
match for a packet from a guest to reach the host at all. A box therefore
cannot spoof another box's source address, cannot dial another box's proxy
listener, and cannot reach any other host address (LAN IP included).
Forwarding from guests is dropped outright: boxes cannot reach each other or
the LAN; the host proxy is the only way out.
"""
import asyncio

from ..config import settings

DNS_PORT = 53
PROXY_PORT = 8443


def render_ruleset(*, table: str = "jarvis_vm", shared_tap: str = "jvtap0",
                   shared_host_ip: str = "10.201.0.1",
                   shared_guest_ip: str = "10.201.0.2",
                   proxy_port: int = PROXY_PORT) -> str:
    """The flag-on ruleset. Pure; the defaults render the checked-in file."""
    return f"""\
# Monitored-egress ruleset, MULTI-BOX mode (vm_boxes_enabled). GENERATED by
# backend/vm/boxnet.render_ruleset() -- edit that and regenerate; a golden-file
# test (tests/test_boxnet.py) holds this file equal to the renderer.
#
# Every guest-facing interface (a KVM box's tap, a docker box's bridge) is in
# @guest_taps. A packet from one reaches the host ONLY if its (iif, saddr) is
# in @tap_src AND its (iif, daddr) is in @tap_addr: no spoofing another box's
# address, no dialing another box's proxy listener, no other host address.
# Then only DNS, the proxy port and ping. Forwarding from guests is dropped:
# boxes cannot reach each other or the LAN. net_box.sh adds/removes the pins.
#
# Self-replacing: the two-line preamble means `nft -f` always starts clean.
table inet {table}
delete table inet {table}

table inet {table} {{
    set cut_hosts {{ type ipv4_addr; flags interval; }}
    set guest_taps {{ type ifname; elements = {{ "{shared_tap}" }} }}
    set tap_addr {{ type ifname . ipv4_addr; elements = {{ "{shared_tap}" . {shared_host_ip} }} }}
    set tap_src {{ type ifname . ipv4_addr; elements = {{ "{shared_tap}" . {shared_guest_ip} }} }}

    chain input {{
        type filter hook input priority -10; policy accept;
        iifname @guest_taps jump guest_input
    }}

    # Guest -> host. Pins first (before conntrack's established accept, so a
    # forged packet cannot ride another box's flow), then the three services.
    chain guest_input {{
        meta nfproto ipv6 counter drop
        # DHCP for the shared box only (its pinned lease; other boxes are
        # configured from box.json): before it has an address its source is
        # 0.0.0.0, which the pins below would drop.
        iifname "{shared_tap}" ip saddr 0.0.0.0 ip daddr 255.255.255.255 udp sport 68 udp dport 67 accept
        iifname . ip saddr != @tap_src limit rate 10/second counter log prefix "jvm-spoof " drop
        iifname . ip saddr != @tap_src counter drop
        iifname . ip daddr != @tap_addr limit rate 10/second counter log prefix "jvm-xbox " drop
        iifname . ip daddr != @tap_addr counter drop
        ct state established,related accept
        udp dport {DNS_PORT} accept
        tcp dport {DNS_PORT} accept
        tcp dport {proxy_port} accept
        icmp type echo-request accept
        limit rate 10/second counter log prefix "jvm-host-drop " drop
        counter drop
    }}

    chain forward {{
        type filter hook forward priority -10; policy drop;
        iifname @guest_taps jump guest_forward
        oifname @guest_taps ct state established,related accept
    }}

    # No guest has a legitimate forward path (all egress is via the host proxy).
    chain guest_forward {{
        ip daddr @cut_hosts counter log prefix "jvm-cut " drop
        counter log prefix "jvm-egress-drop " drop
    }}

    # Host output: a cut host is unreachable even from the proxy itself.
    chain output {{
        type filter hook output priority -10; policy accept;
        ip daddr @cut_hosts counter log prefix "jvm-cut-out " drop
    }}
}}
"""


def _script():
    return settings.base_dir / "vm" / "net" / "net_box.sh"


def net_box_argv(action: str, box) -> list[str]:
    """The exact argv run under sudo (the sudoers line matches this shape)."""
    if action not in ("add", "del", "pin", "unpin"):
        raise ValueError(action)
    return ["sudo", "-n", "bash", str(_script()), action, box.tap,
            box.host_ip, box.guest_ip]


async def _run(action: str, box) -> None:
    proc = await asyncio.create_subprocess_exec(
        *net_box_argv(action, box), stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.PIPE)
    _, err = await proc.communicate()
    if proc.returncode:
        raise RuntimeError(f"net_box.sh {action} {box.tap}: "
                           f"{err.decode(errors='replace')[:300]}")


async def add(box) -> None:
    """Create the box's tap and pin it. Raises on failure (the boot is then
    refused: fail closed)."""
    await _run("pin" if box.runtime == "docker" else "add", box)


async def delete(box) -> None:
    """Unpin and remove. Best-effort: a box going away must finish going."""
    try:
        await _run("unpin" if box.runtime == "docker" else "del", box)
    except (RuntimeError, OSError) as e:
        print(f"[boxes] net del {box.tap} failed: {e}")


if __name__ == "__main__":       # python -m backend.vm.boxnet > vm/net/jarvis-egress-boxes.nft
    print(render_ruleset(), end="")
